//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contingency.GameDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameDataService.GameDataServiceSoap")]
    public interface GameDataServiceSoap {
        
        // CODEGEN: Generating message contract since element name gameId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetState", ReplyAction="*")]
        Contingency.GameDataService.GetStateResponse GetState(Contingency.GameDataService.GetStateRequest request);
        
        // CODEGEN: Generating message contract since element name gameId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRefreshedData", ReplyAction="*")]
        Contingency.GameDataService.GetRefreshedDataResponse GetRefreshedData(Contingency.GameDataService.GetRefreshedDataRequest request);
        
        // CODEGEN: Generating message contract since element name gameId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTeam", ReplyAction="*")]
        Contingency.GameDataService.GetTeamResponse GetTeam(Contingency.GameDataService.GetTeamRequest request);
        
        // CODEGEN: Generating message contract since element name gameId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendState", ReplyAction="*")]
        Contingency.GameDataService.SendStateResponse SendState(Contingency.GameDataService.SendStateRequest request);
        
        // CODEGEN: Generating message contract since element name gameId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NeedsTurn", ReplyAction="*")]
        Contingency.GameDataService.NeedsTurnResponse NeedsTurn(Contingency.GameDataService.NeedsTurnRequest request);
        
        // CODEGEN: Generating message contract since element name gameId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RefreshAvailable", ReplyAction="*")]
        Contingency.GameDataService.RefreshAvailableResponse RefreshAvailable(Contingency.GameDataService.RefreshAvailableRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetState", Namespace="http://tempuri.org/", Order=0)]
        public Contingency.GameDataService.GetStateRequestBody Body;
        
        public GetStateRequest() {
        }
        
        public GetStateRequest(Contingency.GameDataService.GetStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string gameId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string playerId;
        
        public GetStateRequestBody() {
        }
        
        public GetStateRequestBody(string gameId, string playerId) {
            this.gameId = gameId;
            this.playerId = playerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Contingency.GameDataService.GetStateResponseBody Body;
        
        public GetStateResponse() {
        }
        
        public GetStateResponse(Contingency.GameDataService.GetStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetStateResult;
        
        public GetStateResponseBody() {
        }
        
        public GetStateResponseBody(System.Xml.XmlElement GetStateResult) {
            this.GetStateResult = GetStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRefreshedDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRefreshedData", Namespace="http://tempuri.org/", Order=0)]
        public Contingency.GameDataService.GetRefreshedDataRequestBody Body;
        
        public GetRefreshedDataRequest() {
        }
        
        public GetRefreshedDataRequest(Contingency.GameDataService.GetRefreshedDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRefreshedDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string gameId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string playerId;
        
        public GetRefreshedDataRequestBody() {
        }
        
        public GetRefreshedDataRequestBody(string gameId, string playerId) {
            this.gameId = gameId;
            this.playerId = playerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRefreshedDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRefreshedDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Contingency.GameDataService.GetRefreshedDataResponseBody Body;
        
        public GetRefreshedDataResponse() {
        }
        
        public GetRefreshedDataResponse(Contingency.GameDataService.GetRefreshedDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRefreshedDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetRefreshedDataResult;
        
        public GetRefreshedDataResponseBody() {
        }
        
        public GetRefreshedDataResponseBody(System.Xml.XmlElement GetRefreshedDataResult) {
            this.GetRefreshedDataResult = GetRefreshedDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTeamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTeam", Namespace="http://tempuri.org/", Order=0)]
        public Contingency.GameDataService.GetTeamRequestBody Body;
        
        public GetTeamRequest() {
        }
        
        public GetTeamRequest(Contingency.GameDataService.GetTeamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTeamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string gameId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string playerId;
        
        public GetTeamRequestBody() {
        }
        
        public GetTeamRequestBody(string gameId, string playerId) {
            this.gameId = gameId;
            this.playerId = playerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTeamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTeamResponse", Namespace="http://tempuri.org/", Order=0)]
        public Contingency.GameDataService.GetTeamResponseBody Body;
        
        public GetTeamResponse() {
        }
        
        public GetTeamResponse(Contingency.GameDataService.GetTeamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTeamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTeamResult;
        
        public GetTeamResponseBody() {
        }
        
        public GetTeamResponseBody(string GetTeamResult) {
            this.GetTeamResult = GetTeamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendState", Namespace="http://tempuri.org/", Order=0)]
        public Contingency.GameDataService.SendStateRequestBody Body;
        
        public SendStateRequest() {
        }
        
        public SendStateRequest(Contingency.GameDataService.SendStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string gameId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.XmlElement state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string playerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string team;
        
        public SendStateRequestBody() {
        }
        
        public SendStateRequestBody(string gameId, System.Xml.XmlElement state, string playerId, string team) {
            this.gameId = gameId;
            this.state = state;
            this.playerId = playerId;
            this.team = team;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Contingency.GameDataService.SendStateResponseBody Body;
        
        public SendStateResponse() {
        }
        
        public SendStateResponse(Contingency.GameDataService.SendStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendStateResult;
        
        public SendStateResponseBody() {
        }
        
        public SendStateResponseBody(bool SendStateResult) {
            this.SendStateResult = SendStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NeedsTurnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NeedsTurn", Namespace="http://tempuri.org/", Order=0)]
        public Contingency.GameDataService.NeedsTurnRequestBody Body;
        
        public NeedsTurnRequest() {
        }
        
        public NeedsTurnRequest(Contingency.GameDataService.NeedsTurnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NeedsTurnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string gameId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string playerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string team;
        
        public NeedsTurnRequestBody() {
        }
        
        public NeedsTurnRequestBody(string gameId, string playerId, string team) {
            this.gameId = gameId;
            this.playerId = playerId;
            this.team = team;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NeedsTurnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NeedsTurnResponse", Namespace="http://tempuri.org/", Order=0)]
        public Contingency.GameDataService.NeedsTurnResponseBody Body;
        
        public NeedsTurnResponse() {
        }
        
        public NeedsTurnResponse(Contingency.GameDataService.NeedsTurnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NeedsTurnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool NeedsTurnResult;
        
        public NeedsTurnResponseBody() {
        }
        
        public NeedsTurnResponseBody(bool NeedsTurnResult) {
            this.NeedsTurnResult = NeedsTurnResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefreshAvailableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RefreshAvailable", Namespace="http://tempuri.org/", Order=0)]
        public Contingency.GameDataService.RefreshAvailableRequestBody Body;
        
        public RefreshAvailableRequest() {
        }
        
        public RefreshAvailableRequest(Contingency.GameDataService.RefreshAvailableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RefreshAvailableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string gameId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string playerId;
        
        public RefreshAvailableRequestBody() {
        }
        
        public RefreshAvailableRequestBody(string gameId, string playerId) {
            this.gameId = gameId;
            this.playerId = playerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefreshAvailableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RefreshAvailableResponse", Namespace="http://tempuri.org/", Order=0)]
        public Contingency.GameDataService.RefreshAvailableResponseBody Body;
        
        public RefreshAvailableResponse() {
        }
        
        public RefreshAvailableResponse(Contingency.GameDataService.RefreshAvailableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RefreshAvailableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RefreshAvailableResult;
        
        public RefreshAvailableResponseBody() {
        }
        
        public RefreshAvailableResponseBody(bool RefreshAvailableResult) {
            this.RefreshAvailableResult = RefreshAvailableResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GameDataServiceSoapChannel : Contingency.GameDataService.GameDataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameDataServiceSoapClient : System.ServiceModel.ClientBase<Contingency.GameDataService.GameDataServiceSoap>, Contingency.GameDataService.GameDataServiceSoap {
        
        public GameDataServiceSoapClient() {
        }
        
        public GameDataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameDataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameDataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameDataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contingency.GameDataService.GetStateResponse Contingency.GameDataService.GameDataServiceSoap.GetState(Contingency.GameDataService.GetStateRequest request) {
            return base.Channel.GetState(request);
        }
        
        public System.Xml.XmlElement GetState(string gameId, string playerId) {
            Contingency.GameDataService.GetStateRequest inValue = new Contingency.GameDataService.GetStateRequest();
            inValue.Body = new Contingency.GameDataService.GetStateRequestBody();
            inValue.Body.gameId = gameId;
            inValue.Body.playerId = playerId;
            Contingency.GameDataService.GetStateResponse retVal = ((Contingency.GameDataService.GameDataServiceSoap)(this)).GetState(inValue);
            return retVal.Body.GetStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contingency.GameDataService.GetRefreshedDataResponse Contingency.GameDataService.GameDataServiceSoap.GetRefreshedData(Contingency.GameDataService.GetRefreshedDataRequest request) {
            return base.Channel.GetRefreshedData(request);
        }
        
        public System.Xml.XmlElement GetRefreshedData(string gameId, string playerId) {
            Contingency.GameDataService.GetRefreshedDataRequest inValue = new Contingency.GameDataService.GetRefreshedDataRequest();
            inValue.Body = new Contingency.GameDataService.GetRefreshedDataRequestBody();
            inValue.Body.gameId = gameId;
            inValue.Body.playerId = playerId;
            Contingency.GameDataService.GetRefreshedDataResponse retVal = ((Contingency.GameDataService.GameDataServiceSoap)(this)).GetRefreshedData(inValue);
            return retVal.Body.GetRefreshedDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contingency.GameDataService.GetTeamResponse Contingency.GameDataService.GameDataServiceSoap.GetTeam(Contingency.GameDataService.GetTeamRequest request) {
            return base.Channel.GetTeam(request);
        }
        
        public string GetTeam(string gameId, string playerId) {
            Contingency.GameDataService.GetTeamRequest inValue = new Contingency.GameDataService.GetTeamRequest();
            inValue.Body = new Contingency.GameDataService.GetTeamRequestBody();
            inValue.Body.gameId = gameId;
            inValue.Body.playerId = playerId;
            Contingency.GameDataService.GetTeamResponse retVal = ((Contingency.GameDataService.GameDataServiceSoap)(this)).GetTeam(inValue);
            return retVal.Body.GetTeamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contingency.GameDataService.SendStateResponse Contingency.GameDataService.GameDataServiceSoap.SendState(Contingency.GameDataService.SendStateRequest request) {
            return base.Channel.SendState(request);
        }
        
        public bool SendState(string gameId, System.Xml.XmlElement state, string playerId, string team) {
            Contingency.GameDataService.SendStateRequest inValue = new Contingency.GameDataService.SendStateRequest();
            inValue.Body = new Contingency.GameDataService.SendStateRequestBody();
            inValue.Body.gameId = gameId;
            inValue.Body.state = state;
            inValue.Body.playerId = playerId;
            inValue.Body.team = team;
            Contingency.GameDataService.SendStateResponse retVal = ((Contingency.GameDataService.GameDataServiceSoap)(this)).SendState(inValue);
            return retVal.Body.SendStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contingency.GameDataService.NeedsTurnResponse Contingency.GameDataService.GameDataServiceSoap.NeedsTurn(Contingency.GameDataService.NeedsTurnRequest request) {
            return base.Channel.NeedsTurn(request);
        }
        
        public bool NeedsTurn(string gameId, string playerId, string team) {
            Contingency.GameDataService.NeedsTurnRequest inValue = new Contingency.GameDataService.NeedsTurnRequest();
            inValue.Body = new Contingency.GameDataService.NeedsTurnRequestBody();
            inValue.Body.gameId = gameId;
            inValue.Body.playerId = playerId;
            inValue.Body.team = team;
            Contingency.GameDataService.NeedsTurnResponse retVal = ((Contingency.GameDataService.GameDataServiceSoap)(this)).NeedsTurn(inValue);
            return retVal.Body.NeedsTurnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contingency.GameDataService.RefreshAvailableResponse Contingency.GameDataService.GameDataServiceSoap.RefreshAvailable(Contingency.GameDataService.RefreshAvailableRequest request) {
            return base.Channel.RefreshAvailable(request);
        }
        
        public bool RefreshAvailable(string gameId, string playerId) {
            Contingency.GameDataService.RefreshAvailableRequest inValue = new Contingency.GameDataService.RefreshAvailableRequest();
            inValue.Body = new Contingency.GameDataService.RefreshAvailableRequestBody();
            inValue.Body.gameId = gameId;
            inValue.Body.playerId = playerId;
            Contingency.GameDataService.RefreshAvailableResponse retVal = ((Contingency.GameDataService.GameDataServiceSoap)(this)).RefreshAvailable(inValue);
            return retVal.Body.RefreshAvailableResult;
        }
    }
}
